# Generated by Django 3.0.7 on 2020-06-17 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Califas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.CharField(max_length=30)),
                ('alumno', models.CharField(max_length=30)),
                ('cal1', models.IntegerField()),
                ('cal2', models.IntegerField()),
                ('cal3', models.IntegerField()),
            ],
        ),
    ]
